output   = "internal/infra/models"
pkgname  = "models"
wipe     = true
no-tests = true

[psql]
  dbname = "gitscan"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "postgres"
  schema = "gitscan"
  blacklist = ["migrations", "other"]
  sslmode = "disable"
